name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mno_streamer:
    path: ../
  dfunc: ^0.10.0
  universal_io: ^2.2.2
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.1.1
