name: mno_streamer
version: 0.1.1
description: Streamer API and multiple file parsers (PDF, CBZ, Epub) for Dart.
homepage: https://github.com/zentence-reading/mno-streamer-dart
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartx: ^1.0.0
  dfunc: ^0.10.0
  fimber: ^0.7.0
  image: ^4.5.4
  path: ^1.8.0
  universal_io: ^2.0.4
  xml: ^6.5.0
  mno_commons:
    git:
      url: https://github.com/zentence-reading/mno_commons_dart.git
  mno_shared:
    git:
      url: https://github.com/zentence-reading/mno_shared_dart.git
  convert: ^3.1.2
  crypto: ^3.0.6

dev_dependencies:
  coverage: ^1.12.0
  lints: ^5.1.1
  test: ^1.20.1
